Repository weam-ai/weam, pull requests merged in 2025-08, with the labels that each got.

#39 Feature/mcp implementation
  ai-python/requirements.txt
  ai-python/src/MCP/google/gcalendar/calendar_tools.py
  ai-python/src/MCP/google/gdrive/drive_tools.py
  ai-python/src/MCP/google/gmail/gmail_tools.py
  ai-python/src/MCP/google/google_auth.py
  ai-python/src/MCP/google/service_decorator.py
  ai-python/src/MCP/server.py
  ai-python/src/MCP/token_manager.py
  ai-python/src/MCP/utils.py
  ai-python/src/chatflow_langchain/controller/tool_hub.py
  ai-python/src/chatflow_langchain/service/anthropic/tool_functions/tool_service.py
  ai-python/src/chatflow_langchain/service/config/model_config_openai.py
  ai-python/src/chatflow_langchain/service/gemini/tool_functions/tool_service.py
  ai-python/src/chatflow_langchain/service/gemini/tool_functions/tools.py
  ai-python/src/chatflow_langchain/service/multimodal_router/title/title_generator.py
  ai-python/src/chatflow_langchain/service/multimodal_router/tool_functions/tool_service.py
  ai-python/src/chatflow_langchain/service/multimodal_router/tool_functions/tools.py
  ai-python/src/chatflow_langchain/service/o1/tool_functions/tool_service.py
  ai-python/src/chatflow_langchain/service/o1/tool_functions/tools.py
  ai-python/src/chatflow_langchain/service/openai/config/openai_tool_description.py
  ai-python/src/chatflow_langchain/service/openai/tool_functions/tool_service.py
  ai-python/src/chatflow_langchain/service/openai/tool_functions/tools.py
  ai-python/src/content_extraction/text/doc_extractor.py
  ai-python/src/gateway/jwt_decode.py
  ai-python/src/gateway/routers/tool_chat.py
  ai-python/src/gateway/web.py
Labels: MCP

#53 Remove the firebase notification client side data, which is not useful for user
  nextjs/public/firebase-messaging-sw.js
  nodejs/src/services/workspace.js
Labels: enhancement, firebase

#58 feat: currently static remove the credit transaction due to static, only need to setup connect from db logs table
  build.sh
  nextjs/src/app/(page)/settings/credit-control/page.tsx
Labels: todo

#68 Fix/member invitation
  nextjs/src/app/(page)/settings/members/page.tsx
  nextjs/src/components/Auth/CompanyDetails.tsx
  nextjs/src/icons/ResendIcon.tsx
Labels: enhancement

#67 Auto close security issue
  .github/workflows/auto-close-security.yml
Labels: documentation

#77 Feature Enhancements & Code Refactor
  nextjs/package.json
  nextjs/public/Add page.svg
  nextjs/public/Document upload.svg
  nextjs/public/File-download-01.jpg
  nextjs/public/File-download-011212.svg
  nextjs/src/api/list.ts
  nextjs/src/app/(page)/layout.tsx
  nextjs/src/app/(page)/pages/page.tsx
  nextjs/src/app/api/chat/update-response/route.ts
  nextjs/src/app/public/chat/[id]/page.tsx
  nextjs/src/components/Chat/AddPageModal.tsx
  nextjs/src/components/Chat/ChatClone.tsx
  nextjs/src/components/Chat/ChatInput.tsx
  nextjs/src/components/Chat/ChatResponse.tsx
  nextjs/src/components/Chat/DownloadResponse.tsx
  nextjs/src/components/Chat/DownloadTest.tsx
  nextjs/src/components/Chat/EditResponseModal.tsx
  nextjs/src/components/Chat/HoverActionIcon.tsx
  nextjs/src/components/Chat/InlineEditableChatResponse.tsx
  nextjs/src/components/Chat/InlineEditableDemo.tsx
  nextjs/src/components/Chat/InlineEditableResponse.tsx
  nextjs/src/components/Chat/TestPageIcon.tsx
  nextjs/src/components/Dashboard/CompanyListTable.tsx
  nextjs/src/components/Settings/Configuration/APIModelChoose.tsx
  nextjs/src/hooks/chat/usePageOperations.ts
  nextjs/src/hooks/chat/useResponseUpdate.ts
  nextjs/src/icons/AIPagesIcon.tsx
  nextjs/src/icons/CloudIcon.tsx
  nextjs/src/types/chat.ts
  nextjs/src/utils/constant.ts
  nextjs/src/utils/downloadUtils.ts
  nextjs/src/utils/routes.ts
  nodejs/src/controller/fileController.js
  nodejs/src/controller/web/pageController.js
  nodejs/src/models/page.js
  nodejs/src/routes/upload.js
  nodejs/src/routes/web/index.js
  nodejs/src/routes/web/pages.js
  nodejs/src/seeders/permission.json
  nodejs/src/services/chatmember.js
  nodejs/src/services/page.js
  nodejs/src/services/thread.js
  nodejs/src/services/uploadFile.js
  nodejs/src/utils/validations/page.js
  nodejs/src/utils/validations/thread.js
Labels: enhancement
